### ISSUE TITLE
Emacs integration

### ISSUE THREAD

**Issue by anonimitoraf** [jamesdiacono/Replete#1]
Hey man!

I'm predominantly a Clojure dev who has to go back to JS for my day job. Interested in helping out with the implementation of the core features and for more selfish reasons, an integration with Emacs.

So, what's left, where do I start, etc?

Also, how did you solve the problem of redefining/reloading `const` variables, etc?

**Comment by jamesdiacono** [comment]
Great! Replete does not need any work that I'm aware of, but you will need to build an Emacs plugin. Generally, a plugin has these responsibilities:

1. Start, stop and restart the Replete process (replete.js)
2. Send messages containing source code to Replete's STDIN, in response to keyboard shortcuts
3. Display Replete's STDOUT in a text editor window

I can send you the source code of the Sublime Text plugin I hacked together, if you need inspiration.

The problem of redeclaring identifiers is solved in replize_script.js. I recommend that you read the README carefully before continuing.

**Comment by anonimitoraf** [comment]
Sweet, yes please if you can send me the Sublime plugin.

And cool, I'll read the README in detail

**Comment by anonimitoraf** [comment]
Sweet, my question's answered.

Follow up question: I see a bunch of `//debug` lines. Do you mind describing your workflow for these? (I'm guessing it's similar to Clojure `#_`/`comment` but how do you actually run them?)

**Comment by jamesdiacono** [comment]
The `//debug` is a tagged comment. Stripping the tagged comments turns the module into a runnable program, which writes test results to STDOUT.

If you can't be bothered removing them by hand, you can use [ecomcon](https://github.com/douglascrockford/ecomcon). Even better, modify Replete's `source` capability to pass the source thru ecomcon prior to evaluation. That's what I do.

If you are actually going to run Replete's "tests", you will need [jsvalid.js](https://github.com/jamesdiacono/JSValid) and [jscheck.js](https://github.com/douglascrockford/JSCheck).

**Comment by anonimitoraf** [comment]
Ah sweet, thanks! Didn't know about those libs/pkgs

**Comment by anonimitoraf** [comment]
Btw, I get a 418 when I try to access the sublime plugin tar file

**Comment by anonimitoraf** [comment]
Ok, I've some basic Emacs Lisp code that works similar to your Sublime Plugin.

Say I evaluate the following:
```
import os from 'os'
const x = 42;
console.log(x + os.EOL + x);
```
I get
```
42
42
undefined
```

Any way to make it so that STDOUT is distinguishable from the return value? I'm aiming for something like Clojure's CIDER where the return value is printed alongside the code you evaluated like:
https://user-images.githubusercontent.com/15933322/147804071-46d1d8a7-2c42-482e-8f33-9e91955f3bee.mp4

**Comment by jamesdiacono** [comment]
Yep, just modify your "out" capability.

**Comment by anonimitoraf** [comment]
Ah I see. Sweet, thanks!

**Comment by anonimitoraf** [comment]
Just wanted to show you some progress:
https://user-images.githubusercontent.com/15933322/147825258-43957938-9c95-40f0-9e05-1dafac529931.mp4

Very rough atm tho

**Comment by jamesdiacono** [comment]
The better way is to have your Replete process send back JSON-encoded messages, rather than a text stream.

Everything you need is in replete.js. Make yourself a `respond` function, which writes JSON messages wun per line. These will be read wun-at-a-time by your Emacs plugin.

```
function respond(string, type) {
    console.log(JSON.stringify({type, string});
}
```

Modify the capabilities.

```
    out(string) {
        respond(string, "out");
    },
    err(string) {
        respond(string, "err")
    }
```

Modify the `on_message` function. This is the part that I think you are interested in.

```
    return repls[message.platform].send(message).then(
        function (reply) {
            return (
                Array.isArray(reply)
                ? reply.forEach(function (evaluation) {
                    respond(evaluation, "evaluation")
                })
                : respond(reply, "evaluation")
            );
        },
        function (reason) {
            respond(reason, "exception")
        }
    );
```

**Comment by jamesdiacono** [comment]
I realised it was ambiguous for some REPLs to produce an array of evaluations, and other REPLs to produce the evaluation itself. I have committed a change which causes every REPL to produce an array of evaluations. The above change to `on_message` can now be simplified:

```
    return repls[message.platform].send(message).then(
        function (evaluations) {
            return evaluations.forEach(function (evaluation) {
                respond(evaluation, "evaluation")
            })
        },
        function (reason) {
            respond(reason, "exception")
        }
    );
```

**Comment by jamesdiacono** [comment]
I have changed replete.js to respond with JSON messages rather than a text stream. I think this will be better for plugin implementors.

**Comment by anonimitoraf** [comment]
Hey man, thanks for that. I was in the process of doing so, but cool. Sounds good :)

**Comment by anonimitoraf** [comment]
And yes, I think I'll write up a VSCode plugin too

**Comment by jamesdiacono** [comment]
Just a heads up that the structure of the result messages has changed.
```
{type: "evaluation", string: "123"}
```
is now
```
{evaluation: "123"}
```
etc.

**Comment by anonimitoraf** [comment]
Cool, thanks for letting me know

**Comment by jamesdiacono** [comment]
If you would like to share a link to your work, there is now a pinned issue: https://github.com/jamesdiacono/Replete/issues/5.
