### ISSUE TITLE
VSCode plugin issue/question

### ISSUE THREAD

**Issue by adamzerner** [jamesdiacono/Replete#7]
The README for the VSCode plugin says:

> Restart VSCode. The extension must now be configured by navigating to
>    
>    Settings -> User -> Extensions -> Replete
>
> and providing the required paths. Make sure you point to an installation of
Node.js that is version 18.6.0 or higher.

What does "providing the required paths" mean? I don't see anything related to that on the extension page or the extension settings.

<img width="1728" alt="Screenshot 2023-03-13 at 1 20 59 PM" src="https://user-images.githubusercontent.com/3144254/224823375-84cc79fb-84ea-4260-8a0c-62fef624b1d8.png">
<img width="1728" alt="Screenshot 2023-03-13 at 1 21 17 PM" src="https://user-images.githubusercontent.com/3144254/224823401-40b39166-eb4d-4baf-92af-dca3ff7046c7.png">

**Comment by jamesdiacono** [comment]
You need to tell the plugin where to find Node.js, Replete, and optionally Deno. You can find the absolute paths to Node.js and Deno by running `which node` and `which deno` in your terminal. replete.js will be found in the directory you cloned Replete into.

**Comment by jamesdiacono** [comment]
These default paths (each beginning with `C:\`) will not work, you need to replace them with suitable paths for your system (each beginning with `/`, because you are not using Windows).

<img width="695" alt="image" src="https://user-images.githubusercontent.com/86713508/224885692-4f529e27-da8b-4d1f-8c35-552869d0bb61.png">

**Comment by adamzerner** [comment]
I see, thanks for clarifying. However, I made those changes and it still isn't working.

`which node` gives me `/Users/azerner/.nvm/versions/node/v19.8.0/bin/node`. These are the extension settings I have for Replete:

<img width="1728" alt="Screenshot 2023-03-14 at 2 06 42 PM" src="https://user-images.githubusercontent.com/3144254/225136443-05ad7eec-1b17-44d7-9736-a45ccc5972eb.png">

The extension is in the proper directory:

```
extensions/vscode_replete » pwd
/Users/azerner/.vscode/extensions/vscode_replete
```

I restarted VSCode. I can find Replete in the command palette.

<img width="778" alt="Screenshot 2023-03-14 at 2 11 42 PM" src="https://user-images.githubusercontent.com/3144254/225137319-821d5548-5db4-40b2-bb5d-b69f4c082304.png">

But when I try to select it I get the following error:

<img width="269" alt="Screenshot 2023-03-14 at 2 12 12 PM" src="https://user-images.githubusercontent.com/3144254/225137421-f2eca508-bd55-4eb5-88e5-fc797dd0eb45.png">

**Comment by jamesdiacono** [comment]
You must first start Replete before you can evaluate anything. If you search for "Replete" in the command palette you will find the relevant command.

**Comment by jamesdiacono** [comment]
Also, your settings have ended up in the wrong order. The path to `node` should be the first line, not the last line.

**Comment by adamzerner** [comment]
I see. I now have my settings in the following order:
```
/Users/azerner/.nvm/versions/node/v19.8.0/bin/node
/Users/azerner/indeed/Replete/replete.js
--browser_port=52117
--experimental-import-meta-resolve
```
But when I try to start Replete from the command palette with "Replete: Start" I get the following error:
```
file:///Users/azerner/indeed/Replete/replete.js:202
    const [ignore, name, value] = argument.match(/^--(\w+)=(.*)$/);
                                  ^

TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at file:///Users/azerner/indeed/Replete/replete.js:202:35
    at Array.forEach (<anonymous>)
    at file:///Users/azerner/indeed/Replete/replete.js:201:23
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)

Node.js v19.8.0
```

**Comment by jamesdiacono** [comment]
This is the order you want:

```
/Users/azerner/.nvm/versions/node/v19.8.0/bin/node
--experimental-import-meta-resolve
/Users/azerner/indeed/Replete/replete.js
--browser_port=52117
```

The reason is that `--experimental-import-meta-resolve` is an argument of Node.js, whereas  `--browser_port=52117` is an argument of replete.js.

**Comment by adamzerner** [comment]
I see. I updated it to that order, quit VSCode and re-opened it. Then I was able to start Replete successfully, getting an output of `Waiting for WEBL: http://localhost:52117`. However, when I tried to evaluate the highlighted code below I get the following error.

```
SyntaxError: Unexpected token (1:35)
    at pp$4.raise (file:///Users/azerner/indeed/Replete/node_modules/acorn/dist/acorn.mjs:3454:13)
    at pp$9.unexpected (file:///Users/azerner/indeed/Replete/node_modules/acorn/dist/acorn.mjs:755:8)
    at pp$9.expect (file:///Users/azerner/indeed/Replete/node_modules/acorn/dist/acorn.mjs:749:26)
    at pp$5.parseParenAndDistinguishExpression (file:///Users/azerner/indeed/Replete/node_modules/acorn/dist/acorn.mjs:2924:36)
    at pp$5.parseExprAtom (file:///Users/azerner/indeed/Replete/node_modules/acorn/dist/acorn.mjs:2797:41)
    at pp$5.parseExprSubscripts (file:///Users/azerner/indeed/Replete/node_modules/acorn/dist/acorn.mjs:2630:19)
    at pp$5.parseMaybeUnary (file:///Users/azerner/indeed/Replete/node_modules/acorn/dist/acorn.mjs:2596:17)
    at pp$5.parseExprOps (file:///Users/azerner/indeed/Replete/node_modules/acorn/dist/acorn.mjs:2523:19)
    at pp$5.parseMaybeConditional (file:///Users/azerner/indeed/Replete/node_modules/acorn/dist/acorn.mjs:2506:19)
    at pp$5.parseMaybeAssign (file:///Users/azerner/indeed/Replete/node_modules/acorn/dist/acorn.mjs:2473:19)
```

<img width="954" alt="Screenshot 2023-03-15 at 10 35 06 AM" src="https://user-images.githubusercontent.com/3144254/225395464-81d5bd20-be53-4a6b-8af2-ba9a596085bb.png">

**Comment by jamesdiacono** [comment]
If you need Replete to support transpiled languages (such as TypeScript, which I see you are using) then some extra configuration is required. See #6.

**Comment by adamzerner** [comment]
Gotcha. I ran into an issue and commented on #6.
