### ISSUE TITLE
VS Code Plugin

### ISSUE THREAD

**Issue by aelbaitam** [jamesdiacono/Replete#8]
I tried several different options to set the path to replete.js but none worked. Starting Replete from VS Code throws an error that it can't find C:\C:\path\to\replete. If I try relative path it tries to find it under C:\Program Files\Microsoft VS Code\ directory. I move the directory there but it also didn't work. I tried to set the path using file:///C:/ but didn't work also.

How should I specify the absolute path to replete.js on windows? Assume it is in C:\Replete for example.

I can't wait to try this plugin, thanks for working on it James.

**Comment by jamesdiacono** [comment]
It depends on where you cloned the Replete repository to. If you cloned it into C:\Replete, the path to replete.js will be C:\Replete\replete.js. If that doesn't work, post a screenshot of your settings.

**Comment by aelbaitam** [comment]
Here's the error I am getting:

Waiting for WEBL: http://localhost:52117
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\C:\Replete\cmdl\node_padawan.js' imported from C:\Program Files\Microsoft VS Code\
    at new NodeError (node:internal/errors:399:5)
    at finalizeResolution (node:internal/modules/esm/resolve:326:11)
    at moduleResolve (node:internal/modules/esm/resolve:945:10)
    at defaultResolve (node:internal/modules/esm/resolve:1153:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at resolve (file:///C:/Replete/cmdl/node_loader.js:21:12)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:525:22) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.15.0

**Comment by aelbaitam** [comment]
![image](https://user-images.githubusercontent.com/56499350/227457257-bf0bda7f-fd53-4805-80d1-f07f7a77599f.png)

![image](https://user-images.githubusercontent.com/56499350/227457412-1581753c-7874-46da-badd-72bffbe88128.png)

**Comment by jamesdiacono** [comment]
Can you add a log statement to C:\Replete\cmdl\node_cmdl.js and tell me what it prints?

Add this before line 38: `console.error(padawan_url);`

**Comment by jamesdiacono** [comment]
Maybe add these too:
```
console.error(padawan_url.pathname);
console.error(import.meta.url);
```

**Comment by aelbaitam** [comment]
It prints 

/C:/Replete/cmdl/node_padawan.js
file:///C:/Replete/cmdl/node_cmdl.js


The complete error now is:
/C:/Replete/cmdl/node_padawan.js
file:///C:/Replete/cmdl/node_cmdl.js
Waiting for WEBL: http://localhost:52117
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\C:\Replete\cmdl\node_padawan.js' imported from C:\Program Files\Microsoft VS Code\
    at new NodeError (node:internal/errors:399:5)
    at finalizeResolution (node:internal/modules/esm/resolve:326:11)
    at moduleResolve (node:internal/modules/esm/resolve:945:10)
    at defaultResolve (node:internal/modules/esm/resolve:1153:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at resolve (file:///C:/Replete/cmdl/node_loader.js:21:12)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:525:22) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.15.0

**Comment by jamesdiacono** [comment]
This is my fault, I will fix it. In the meantime, you can still use Replete with the browser (just navigate to http://localhost:52117/ after starting Replete).

**Comment by jamesdiacono** [comment]
Please try this. Add `import url from "url";` to the list of imports in node_cmdl.js. Then replace the line
```
node_args.concat(padawan_url.pathname, String(tcp_port)),
```
with
```
node_args.concat(url.fileURLToPath(padawan_url), String(tcp_port)),
```
I think that should fix it.

**Comment by aelbaitam** [comment]
When I press Ctrl+Alt+Shift+B it actually evaluates in the console.

**Comment by aelbaitam** [comment]
The log lines (didn't remove them)
/C:/Replete/cmdl/node_padawan.js
file:///C:/Replete/cmdl/node_cmdl.js

Waiting for WEBL: http://localhost:52117
WEBL found.

It worked.

hello world
3

**Comment by aelbaitam** [comment]
Thanks James. It works. I have a problem with the Ctrl+Alt+Shift+N keybinding. It shows @ in the command pallete if I choose Replete>Evaluate in Node it works. I'll have to fix the keybinding. 

Is there a command I could clear the output window?

**Comment by jamesdiacono** [comment]
Great, thanks for your help. You can change the keybindings in the Keyboard Shortcuts section of VSCode (search the keybindings for "Replete").

I'm not sure how to clear the output window with a keybinding, but you can click the "clear" button:
<img width="416" alt="image" src="https://user-images.githubusercontent.com/86713508/227465730-2f945d1a-b0d5-43b1-8854-01382604e25f.png">
Please let me know if you find out how to clear it with a keybinding.

Ctrl+Alt+Shift+B should definitely evaluate code in the browser. Try evaluating `navigator.userAgent`.

**Comment by aelbaitam** [comment]
I am using the Clear button as well but couldn't find a way to add a keybinding but that's not related to the issue which can be closed now. Thanks for your quick responses and help James.

**Comment by jamesdiacono** [comment]
I've pushed a fix. You can get the latest by doing a `git pull` from C:\Replete.

**Comment by jamesdiacono** [comment]
I have added a keybinding to clear the output (ctrl+alt+shift+L), you can get the latest plugin [here](https://james.diacono.com.au/files/vscode_replete.zip).
